### ISSUE TITLE
AssertionError when no DICOM files found in patient folder

### ISSUE THREAD

**Issue by miragessee** [MaxenceLarose/delia#8]
I am trying to create a patient database using the PatientsDatabase class from the delia package. However, I am encountering an AssertionError stating that no DICOM files are found in the patient folder.

**Environment:**

Python version: 3.10.11
OS: Windows
Delia version: 1.2.6

**Error:**
AssertionError: The patient folder must contain DICOM files. This is not the case for the patient whose data is currently being downloaded since no DICOM files are found in its folder.

**Code:**
```
from delia.databases import PatientsDatabase
from delia.extractors import PatientsDataExtractor

patients_data_extractor = PatientsDataExtractor(path_to_patients_folder=r"C:\dicom_folder")
database = PatientsDatabase(path_to_database=r"C:\dicom_folder\patients_database.h5")
database.create(patients_data_extractor=patients_data_extractor, overwrite_database=True)
```

The folder in question does contain .dcm files, yet the program throws an AssertionError stating otherwise.

**Comment by MaxenceLarose** [comment]
Greetings! We greatly appreciate your interest in the DELIA package.

To clarify, the `path_to_patients_folder` parameter should point to a directory housing multiple subfolders, each dedicated to an individual patient. Within these patient-specific folders, you'll find their respective .dcm files, organized as demonstrated [here](https://github.com/MedPhysUL/delia#structure-your-patients-directory).

Should you have any specific inquiries or require further assistance with the DELIA package, please don't hesitate to reach out. We're here to help!

**Comment by miragessee** [comment]
> Greetings! We greatly appreciate your interest in the DELIA package.
> 
> To clarify, the `path_to_patients_folder` parameter should point to a directory housing multiple subfolders, each dedicated to an individual patient. Within these patient-specific folders, you'll find their respective .dcm files, organized as demonstrated [here](https://github.com/MedPhysUL/delia#structure-your-patients-directory).
> 
> Should you have any specific inquiries or require further assistance with the DELIA package, please don't hesitate to reach out. We're here to help!

Yes, your answer solved the problem, but I tried to use the h5 file I created with DELIA in a project like in this link and failed (https://github.com/paulojamorim/panoramic_generator). What I want to do is to view the h5 file as a panoramic view. What do you suggest to do this or is it a feature that can be added to the DELIA package in the future?

**Comment by MaxenceLarose** [comment]
I suggest looking into the specific structure the `panoramic_generator` expects the HDF5 file to have. You can then try to create a function that modifies the HDF5 file generated by DELIA to match the structure of the application you want to use.

Hope it helps!
